version: "3"

services:
  server:
    build:
      context: .
    container_name: MagicBox
    restart: always
    init: true
    volumes:
      - "$PWD/configs:/app/configs"
      - "$PWD/MagicBox.log:/app/MagicBox.log"
    environment:
      - "TZ=Asia/Shanghai"
