version: "3"

services:
  server:
    image: srcrs/magicbox:latest
    container_name: MagicBox
    restart: always
    init: true
    volumes:
      - "$PWD/configs:/app/configs"
      - "$PWD/examples:/app/examples"
      - "$PWD/MagicBox.log:/app/MagicBox.log"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 9222:9222
